obj-y += blk.o
obj-y += entry.o
obj-y += main.o
obj-y += pci.o
obj-y += plic.o
obj-y += proc.o
obj-y += swtch.o
obj-y += syscall.o
obj-y += timer.o
obj-y += trap_entry.o
obj-y += trap.o
obj-y += uart.o
obj-y += usr.o
obj-y += virtio.o
obj-y += vmm.o


ccflags-y += -DNSTACK=$(SMP)
